CREATE TABLE `my_plant` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT(20) UNSIGNED NOT NULL,
	`farm_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`current_state` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
